blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/yourusername/mvdb/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/yourusername/mvdb/tree/main/docs
    about: Check our documentation for detailed guides and references.
